name: directbot
version: 1.0.0
description: DirectCode IRC Bot
dependencies:
  http: 0.11.1+1
  irc: 1.3.2
  quiver: 0.18.2
  yaml: 0.10.0
  math_expressions: ">=0.0.9 <0.1.0"
environment:
  sdk: ">=1.6.0-dev"
