name: directbot
version: 1.0.0
description: DirectCode IRC Bot
dependencies:
  http: 0.11.1+1
  irc: 1.3.4
  quiver: 0.19.0-dev.2
  yaml: 1.1.1
  math_expressions: ">=0.0.9 <0.5.0"
environment:
  sdk: ">=1.5.0"
